### ISSUE TITLE
Comments bot framework

### ISSUE THREAD

**Issue by jdd-software** [SOBotics/Nursery#7] opened 2018-05-10 07:13 UTC
**Name of the bot:** ??
**General topic:** Monitor comments
**Requires feedback:** If desired yes, using higgs
**Problem, the bot is supposed to solve:**  
Possibility for anyone that wants to monitor comments from any SE site in any SE chat.

This is a bot framework that one can easily setup and start to monitor comments on any SE chat. It will call the HeatDetector api to get classification/regex info related to the comments.

Some basic bot configuration (we need to discuss this)
1. Bot account to use
2. Chat room to join
3. Api key for SE api
4. Api key for HeatDetector Api
5. If feedback is desired botId and api key for Higgs.

Some basic bot functions (we need to discuss this)
1. Add SE site to monitor
2. Setup thresholds (hence when to report, example -all, score>4, perspective>0.95 etc)
   a) for output in chat
   b) for when to ping

**Ideas for implementation:**
Either we develop something new or we adapt one of the similar projects that we already have like [Citation-Dector](https://github.com/SOBotics/Citation-Detector) and comments-monitor also Mithrandir has a bot for IPS.

What would be important is; yes we can have one of these bots running if people need something quick for a special site that is being trolled, but my idea is that other sites can setup there own bots, hence create bot user, request SE api-key and then configure the bot to run in a room of there choice.

**Comment by Bhargav-Rao** [comment] 2018-05-10 07:17
Semi Duplicate of https://github.com/SOBotics/Boson

**Comment by jdd-software** [comment] 2018-05-10 07:18
Yes that could also be the starting frame work, but it needs to be simple to use for people, hence if Boson does more things, we need to understand how we make it not do complicate to configure.

**Comment by Bhargav-Rao** [comment] 2018-05-10 07:19
The plan is `@Boson monitor comments on IPS` should start monitoring all comments on IPS, which is pretty simple use...

**Comment by jdd-software** [comment] 2018-05-10 07:22
Great but you would need implementation to new HeatDetector api (+Higgs if feedback is desired) and we need to figure out how we can make it easy to configure (hence when to output comment in chat and when to ping which user)

**Comment by superplane39** [comment] 2018-05-10 07:29
Also relevant: https://github.com/superplane39/GetAllTehCommentz/

**Comment by Bhargav-Rao** [comment] 2019-03-10 06:45
Heat Detector filter and Higgs dash is now implemented in Boson. https://github.com/SOBotics/Boson/blob/master/docs/commands.md#filters

**Closed as completed by Bhargav-Rao** 2019-03-10 06:45 UTC
Labels: bot-idea, in-discussion
